const types = {
    SET_DOG_FILTER: 'SET_DOG_FILTER',
    FETCH_DOGS: 'FETCH_DOGS',
    SET_DOG_LIST: 'SET_DOG_LIST',
    SET_DOG_IMG: 'SET_DOG_IMG',
    SET_DOG_IMG_ERROR: 'SET_DOG_IMG_ERROR',
    SET_DOG_LIST_ERROR: 'SET_DOG_LIST_ERROR'
};

export default types;
